// app/layout.js
import './globals.css'
import ClientRoot from './components/ClientRoot'
import { ToastProvider } from './components/ui/Toast'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const ADD_GPTW = true

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body {...(ADD_GPTW ? { 'data-gptw': '' } : {})}>
    <ClientRoot>
      <ToastProvider>
        <main>
                   <div className='fixed inset-0 star-field pointer-events-none'></div>
  <div className='fixed inset-0 star-field-2 pointer-events-none'></div>
  
  <div className='fixed inset-0 cosmic-dust pointer-events-none'></div>
          {children}</main>
      </ToastProvider>
      </ClientRoot>
      </body>
    </html>
  )
}
