// app/layout.js
import './globals.css'
import ClientRoot from './components/ClientRoot'
import { ToastProvider } from './components/ui/Toast'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const ADD_GPTW = true

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body {...(ADD_GPTW ? { 'data-gptw': '' } : {})}>
        <ClientRoot>
          <ToastProvider>
              {children}
          </ToastProvider>
        </ClientRoot>
      </body>
    </html>
  )
}
